name: Compilar Quiosco iOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Descargar el codigo del repositorio
      uses: actions/checkout@v4.2.2 # Versión actualizada

    - name: Instalar Node.js
      uses: actions/setup-node@v4.2.0 # Versión actualizada
      with:
        node-version: 22 # Subimos a Node 22 para evitar warnings

    - name: Instalar Cordova
      run: npm install -g cordova

    - name: Crear Proyecto Cordova
      run: |
        cordova create app com.smitel.quiosco QuioscoSmitel
        cd app
        cordova platform add ios
        
        # Mover tu HTML y Logo a la carpeta de la app
        rm www/index.html
        cp ../index.html www/
        cp ../logo.png www/
        
        # Instalar plugin de la camara
        cordova plugin add cordova-plugin-camera

    - name: Preparar archivos para Xcode
      run: |
        cd app
        cordova prepare ios

    - name: Compilar App (Forzar destino y ruta)
      run: |
        cd app/platforms/ios
        xcodebuild -workspace QuioscoSmitel.xcworkspace -scheme QuioscoSmitel -configuration Debug -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO CONFIGURATION_BUILD_DIR=build/output

    - name: Guardar el archivo ejecutable resultante
      uses: actions/upload-artifact@v4
      with:
        name: App-Quiosco-Smitel
        path: app/platforms/ios/build/output/QuioscoSmitel.app
